[package]
name = "modelversus-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_rust"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.25.0"
features = ["extension-module", "auto-initialize"]
[dependencies.tch]
version = "0.19.0"
[dependencies]
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread", "time"] }
futures = "0.3.31"
numpy = "0.25.0"
once_cell = "1.21.3"